name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Headless
      working-directory: ./dioxycomp-headless
      run: cargo build --verbose 
      
    # - name: Build Example/Demo
    #   working-directory: examples/demo
    #   run: cargo build --verbose
    - name: Run Tests on Headless
      working-directory: ./dioxycomp-headless
      run: cargo test --verbose
